# .github/workflows/fs-test.yml
name: File System Test

on:
  push:
    branches: [ main, master ]  # 支持main或master分支
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  test-fs:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build/bin/Release
        ./fs_test.exe > result_win.txt
      shell: cmd

    - name: Run Test (Unix-like)
      if: matrix.os != 'windows-latest'
      run: |
        cd build/bin
        ./fs_test > result_$(uname).txt

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}
        path: |
          build/bin/result_*.txt
          build/bin/Release/result_*.txt