name: File System Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-fs:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Build
      run: cmake --build build --config Release
      shell: bash

    - name: Run Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build\bin\Release
        echo "=== Windows Test Results ===" > result_win.txt
        echo "Current Directory: %CD%" >> result_win.txt
        .\fs_test.exe >> result_win.txt
        type result_win.txt
      shell: cmd

    - name: Run Test (Unix-like)
      if: matrix.os != 'windows-latest'
      run: |
        cd build/bin
        echo "=== $(uname) Test Results ===" > result_$(uname).txt
        echo "Current Directory: $(pwd)" >> result_$(uname).txt
        ./fs_test >> result_$(uname).txt
        cat result_$(uname).txt
      shell: bash

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}
        path: |
          build/bin/result_*.txt
          build/bin/Release/result_*.txt

    # 添加一个汇总步骤
    - name: Summarize Results
      run: |
        echo "### Test Results for ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cat build/bin/Release/result_win.txt >> $GITHUB_STEP_SUMMARY
        else
          cat build/bin/result_*.txt >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash